### PR TITLE
Update to CEF 3.3202.1692.g18a939d

### PR DESCRIPTION
**Pull request by fenryxo**

### CODE REVIEW

**Comment by cztomczak** [comment]
1. Only the include/ directory was updated? There were no changes required to capi/ root directory?
2. Looks like you have updated include/ directory with include/ directory from Linux binary distribution. You should have used include/ directory from the CEF repository from bitbucket at appropriate revision. Windows and Mac specific files are missing.
3. After point 2) is fixed see also the notes on "cef_version_win.h" and "cef_version_linux.h"
4. Have you tested it on Windows?
5. Patch for GCC compiler on Windows is no more required, so README.md should be updated

**Comment by cztomczak** [comment]
6. You've added C++ header files which are unnecessary and should be deleted (files in include/, include/views/ and include/wrapper/)

**Comment by fenryxo** [comment]
1. It builds and runs without any changes in the capi/ root directory.
2. Fixed: Copied files from CEF git 18a939d.
3. Fixed: Copied version headers from win & linux binary distributions.
4. I have no opportunity to test CEF on Windows.
5. Readme updated.
6. Fixed: C++ headers removed.

**Comment by cztomczak** [comment]
Looks good now. Only the Compatibility section for Windows needs to be updated in README.md.

**Comment by fenryxo** [comment]
It would be better to test it on Windows before claiming it's a tested configuration.

**Comment by cztomczak** [comment]
It works on Windows. Only seeing some warnings in console, but everything seems to be working fine. Logs:

```cmd
[1205/194447.310:WARNING:PushPullFIFO.cpp(182)] PushPullFIFO: underflow while pulling (underflowCount=1, avail
ableFrames=0, requestedFrames=448, fifoLength=8192)
[1205/194447.370:WARNING:angle_platform_impl.cc(51)] rx::HLSLCompiler::compileToBinary(228):
C:\fakepath(71,11-35): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally hand
le negative values if you expect them
C:\fakepath(95,11-35): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally hand
le negative values if you expect them
```

**Comment by fenryxo** [comment]
Great :+1: Which Windows and compiler version should I update the readme with?

**Comment by cztomczak** [comment]
Just update the revision.

**Comment by fenryxo** [comment]
Done.

**Comment by cztomczak** [comment]
cef_version_win.h needs updating as well to match.

**Comment by fenryxo** [comment]
Hm, it seems that the Windows binary distribution lagged behind the Linux one when I downloaded them. Corrected.

**Comment by cztomczak** [comment]
Thanks, merged.

**Comment by cztomczak** [comment]
Add yourself to the Authors file in next PR.

**Pull request merged**
